version: "3.7"

services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome
    shm_size: '2gb'
    ports:
      - "5900"
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      JAVA_OPTS: -Dwebdriver.chrome.whitelistedIps=

  firefox:
    image: selenium/node-firefox
    shm_size: '2gb'
    ports:
      - "5901"
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      JAVA_OPTS: -Dwebdriver.chrome.whitelistedIps=

networks:
  default:
    name: grid